version: '3.8'
services:
    app:
        build: .
        ports:
            - '8000:80'
        volumes:
            - './:/var/www/html'
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: '3306'
    db:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            POSTGRES_PASSWORD: secret
        volumes:
            - 'db_data:/var/lib/mysql'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: secret
        depends_on:
            - db
volumes:
    db_data: {  }
